name: avora
description: AVORA cross-platform social voice/video/live app starter.
publish_to: "none"
version: 0.1.0+25

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.8.0
  country_picker: ^2.0.27
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  flutter:
    sdk: flutter
  google_sign_in: 6.3.0
  image_picker: ^1.1.2
  zego_express_engine: ^3.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.2.0

flutter:
  uses-material-design: true
